export const categories = [
  { value: 'Food', label: 'Food', type: 'expense' },
  { value: 'Transport', label: 'Transport', type: 'expense' },
  { value: 'Entertainment', label: 'Entertainment', type: 'expense' },
  { value: 'Shopping', label: 'Shopping', type: 'expense' },
  { value: 'Bills', label: 'Bills & Utilities', type: 'expense' },
  { value: 'Health', label: 'Health', type: 'expense' },
  { value: 'Education', label: 'Education', type: 'expense' },
  { value: 'Travel', label: 'Travel', type: 'expense' },
  { value: 'Gifts & Donations', label: 'Gifts & Donations', type: 'expense' },
  { value: 'Personal Care', label: 'Personal Care', type: 'expense' },
  { value: 'Rent', label: 'Rent', type: 'expense' },
  { value: 'Pets', label: 'Pets', type: 'expense' },
  { value: 'Subscriptions', label: 'Subscriptions', type: 'expense' },
  { value: 'Childcare', label: 'Childcare', type: 'expense' },
  { value: 'Debt', label: 'Loan & Debt Repayment', type: 'expense' },
  { value: 'Emergency', label: 'Emergency', type: 'expense' },
  { value: 'Miscellaneous', label: 'Miscellaneous', type: 'expense' },

  { value: 'Work', label: 'Work & Freelance', type: 'income' },
  { value: 'Savings', label: 'Savings', type: 'income' },
  { value: 'Investments', label: 'Investments', type: 'income' },
  { value: 'Freelance', label: 'Freelance', type: 'income' },
  { value: 'Gift Income', label: 'Gift Income', type: 'income' },
  { value: 'Interest', label: 'Bank Interest', type: 'income' },
  { value: 'Salary', label: 'Salary', type: 'income' },
  { value: 'Refund', label: 'Refunds / Cashback', type: 'income' },
];
