export const categories = [
  { value: 'Food', label: 'Food' },
  { value: 'Transport', label: 'Transport' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Shopping', label: 'Shopping' },
  { value: 'Bills', label: 'Bills & Utilities' },
  { value: 'Health', label: 'Health' },
  { value: 'Education', label: 'Education' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Gifts & Donations', label: 'Gifts & Donations' },
  { value: 'Savings', label: 'Savings' },
  { value: 'Investments', label: 'Investments' },
  { value: 'Personal Care', label: 'Personal Care' },
  { value: 'Rent', label: 'Rent' },
  { value: 'Work', label: 'Work & Freelance' },
  { value: 'Pets', label: 'Pets' },
  { value: 'Subscriptions', label: 'Subscriptions' },
  { value: 'Childcare', label: 'Childcare' },
  { value: 'Debt', label: 'Loan & Debt Repayment' },
  { value: 'Emergency', label: 'Emergency' },
  { value: 'Miscellaneous', label: 'Miscellaneous' },
];
